### ISSUE TITLE
couldn't find "libpl_droidsonroids_gif.so"

### ISSUE THREAD

**Issue by jignesh8992** [koral--/android-gif-drawable-eclipse-sample#1]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.morninggif-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.morninggif-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libpl_droidsonroids_gif.so"

**Comment by jignesh8992** [comment]
05-26 16:30:49.761: E/AndroidRuntime(22098): FATAL EXCEPTION: main
05-26 16:30:49.761: E/AndroidRuntime(22098): Process: com.example.morninggif, PID: 22098
05-26 16:30:49.761: E/AndroidRuntime(22098): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.morninggif-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.morninggif-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libpl_droidsonroids_gif.so"
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at java.lang.Runtime.loadLibrary(Runtime.java:367)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at java.lang.System.loadLibrary(System.java:1076)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at pl.droidsonroids.gif.GifInfoHandle.<clinit>(GifInfoHandle.java:41)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:150)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at pl.droidsonroids.gif.GifDrawable.<init>(GifDrawable.java:88)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at com.example.morninggif.GifAdapter.getView(GifAdapter.java:89)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.widget.AbsListView.obtainView(AbsListView.java:2346)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.widget.GridView.onMeasure(GridView.java:1065)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.view.View.measure(View.java:18811)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:716)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:462)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.view.View.measure(View.java:18811)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.view.View.measure(View.java:18811)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:446)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.view.View.measure(View.java:18811)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5952)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.view.View.measure(View.java:18811)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2127)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1243)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1479)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1134)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6050)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:860)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.view.Choreographer.doCallbacks(Choreographer.java:672)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.view.Choreographer.doFrame(Choreographer.java:608)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:846)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.os.Handler.handleCallback(Handler.java:742)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.os.Looper.loop(Looper.java:154)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at android.app.ActivityThread.main(ActivityThread.java:5527)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at java.lang.reflect.Method.invoke(Native Method)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
05-26 16:30:49.761: E/AndroidRuntime(22098): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
05-26 16:30:55.464: E/System(22098): Uncaught exception thrown by finalizer
05-26 16:30:55.464: E/System(22098): java.lang.UnsatisfiedLinkError: pl.droidsonroids.gif.GifInfoHandle
05-26 16:30:55.464: E/System(22098): 	at pl.droidsonroids.gif.GifInfoHandle.finalize(GifInfoHandle.java:225)
05-26 16:30:55.464: E/System(22098): 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:235)
05-26 16:30:55.464: E/System(22098): 	at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:222)
05-26 16:30:55.464: E/System(22098): 	at java.lang.Thread.run(Thread.java:818)

**Comment by koral--** [comment]
Could you unzip APK file and check if arm64 binary is present there?
